# Generated by Django 3.2.5 on 2021-07-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='denegado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credito',
            name='puntuacionSentinel',
            field=models.CharField(choices=[(1, 'mala'), (2, 'regular'), (3, 'buena')], default=1, max_length=2),
        ),
    ]
