# Generated by Django 3.2.5 on 2021-07-06 22:54

from django.db import migrations
import finanzas.utils


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_credito_puntuacionia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='monto',
            field=finanzas.utils.IntegerRangeField(),
        ),
    ]
